FROM centos:7 AS builder

LABEL stage=gobuilder

# install gcc
# -y means saying yes to all questions
RUN yum install -y gcc
#https://blog.csdn.net/fjx1173865548/article/details/89631291
RUN yum install -y epel-release

# install golang
RUN yum install -y go

# config GOROOT
ENV GOROOT /usr/lib/golang
ENV PATH=$PATH:/usr/lib/golang/bin

# config GOPATH
RUN mkdir -p /root/gopath
RUN mkdir -p /root/gopath/src
RUN mkdir -p /root/gopath/pkg
RUN mkdir -p /root/gopath/bin
ENV GOPATH /root/gopath

ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOPROXY https://goproxy.cn,direct

WORKDIR /build/zero
COPY . .
RUN sh -c "[ -f go.mod ]" || exit
COPY rpc/add/etc /app/etc
RUN go build -ldflags="-s -w" -o /app/add rpc/add/add.go


FROM centos:7

RUN apk update --no-cache
RUN apk add --no-cache ca-certificates
RUN apk add --no-cache tzdata
ENV TZ Asia/Shanghai

WORKDIR /app
COPY --from=builder /app/add /app/add
COPY --from=builder /app/etc /app/etc

CMD ["./add", "-f", "etc/add.yaml"]
